### ISSUE TITLE
getting started + submission

### ISSUE THREAD

**Issue by cameronjacoby** [sf-wdi-24/ruby-oop-reading#1]
@ben-manning Can you make it clearer at the bottom of the reading that the "exercises" are HW they should be turning in? i.e. Add instructions for "Getting Started" (fork + clone) and "Submission". Also, instead of the `solution.rb` file, could you make a solution branch that contains those solutions to keep it consistent with other HW repos?

**Comment by ben-manning** [comment]
@cameronjacoby I think I've cleared up the directions for the students to follow on this reading.  I've also got the branches separated so it should be a little more uniform throughout.
